# Dependencies
markdown:         kramdown


# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            nw19a
tagline:          'Sofwaretechnik Praktikum'
description:      'Webauftritt der SWTP Gruppe nw19a. Simulation von Poi-Figuren'
url:              https://pcai042.informatik.uni-leipzig.de/~nw19a/Website
baseurl:          /

author:
  name:         'Thomas Pause'
  url:          https://github.com/ThomasPause

# Custom vars

webmaster:      "Thomas Pause"
githubTP:       https://github.com/ThomasPause

# paginate:         5

version:        0.8.0

github:
  repo:         https://github.com/ThomasPause/SWTPnw19aProjectHomepage
